name: "Apply issue labels to PR"

on:
  pull_request:
    types: [opened]

jobs:
  label_on_pr:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Apply labels from linked issue to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_DATA: ${{ toJson(github.event.pull_request) }}
        run: node ./.github/workflows/scripts/apply-issue-labels-to-pr.ts
